# NB! when updating make sure the version is in sync with:
# * rasa version in requirements.txt
# * RASA_VERSION and RASA_X_VERSION  in .github/workflows/continuous-deployment.yml
# Pull SDK image as base image
FROM rasa/rasa:3.2.0-full

# Use subdirectory as working directory
WORKDIR /app

# Copy actions requirements
COPY . .

# Start the action server
CMD ["run"]
# CMD ["start"]
